name: Build app

on:
  workflow_call:
    inputs:
      build-tag:
        required: false
        type: string
        description: "Tag/branch/ref to build"
        default: main
    outputs:
      tag:
        description: "Build tag"
        value: ${{ jobs.build-app.outputs.tag }}
      image:
        description: "Image"
        value: ${{ jobs.build-app.outputs.image }}

jobs:
  build-app:
    name: Build app
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    outputs:
      tag: ${{ steps.docker-build-push.outputs.tag }}
      image: ${{ steps.docker-build-push.outputs.image }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          ref: ${{ inputs.build-tag }}
      - name: Install Java 21
        uses: actions/setup-java@v5
        with:
          java-version: 21
          distribution: temurin
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5
        with:
          cache-overwrite-existing: true
          cache-encryption-key: ${{ secrets.GRADLE_ENCRYPTION_KEY }}
      - name: Build and test
        run: ./gradlew build
        env:
          ORG_GRADLE_PROJECT_githubUser: x-access-token
          ORG_GRADLE_PROJECT_githubPassword: ${{ secrets.GITHUB_TOKEN }}
      - name: Build & push Docker image
        uses: nais/docker-build-push@v0
        id: docker-build-push
        with:
          team: klage
          tag: ${{ github.sha }}
          build_args: |
            VERSION=${CI}
      - name: Log Docker image tag
        run: echo "Docker image tag = ${{ steps.docker-build-push.outputs.tag }}"