name: Build app

on:
  workflow_call:
    outputs:
      tag:
        description: "Build tag"
        value: ${{ jobs.build-app.outputs.tag }}
      image:
        description: "Image"
        value: ${{ jobs.build-app.outputs.image }}

jobs:
  build-app:
    name: Build app
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    outputs:
      tag: ${{ steps.docker-build-push.outputs.tag }}
      image: ${{ steps.docker-build-push.outputs.image }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - name: Install Java 21
        uses: actions/setup-java@v5
        with:
          java-version: 21
          distribution: temurin
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5
        with:
          cache-overwrite-existing: true
          cache-encryption-key: ${{ secrets.GRADLE_ENCRYPTION_KEY }}
      - name: Build and test
        run: ./gradlew build
        env:
          ORG_GRADLE_PROJECT_githubUser: x-access-token
          ORG_GRADLE_PROJECT_githubPassword: ${{ secrets.GITHUB_TOKEN }}
      - name: Build & push Docker image
        uses: nais/docker-build-push@v0
        id: docker-build-push
        with:
          team: klage # required
          tag: ${{ github.sha }} # optional
          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }} # required, but is defined as an organization secret
          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }} # required, but is defined as an organization variable
          build_args: |
            VERSION=${CI}
      - name: Post failures to Slack
        if: failure()
        run: |
          curl -X POST --data-urlencode "payload={\"channel\": \"$CHANNEL\", \"text\": \"$MESSAGE\", \"icon_emoji\": \":ghost:\"}" $WEBHOOK_URL
        env:
          MESSAGE: "Bygg feilet"
          CHANNEL: "#klage-notifications"
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}