on:
  workflow_call:
    inputs:
      image:
        required: true
        type: string
      nav-cluster:
        required: true
        type: string
      nav-environment:
        required: true
        type: string

jobs:
  deploy-nais-app:
    name: Deploy to ${{ inputs.nav-environment }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          sparse-checkout: |
            nais/**
          sparse-checkout-cone-mode: false
      - uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: ${{ inputs.nav-cluster }}
          RESOURCE: nais/nais.yaml
          VARS: nais/${{ inputs.nav-environment }}-config.yaml
          VAR: image=${{ inputs.image }}