name: Deploy build-tag to prod

on:
  workflow_call:
    inputs:
      image:
        required: true
        type: string
      tag:
        description: "Build tag"
        type: string
        required: true
      nav-cluster:
        required: false
        type: string
        description: Nais cluster in prod to deploy to
        default: 'prod-gcp'

jobs:
  deploy-to-prod:
    uses: navikt/klage-workflows/.github/workflows/deploy-nais-app.yaml@main
    with:
      image: ${{ inputs.image }}
      nav-cluster: ${{ inputs.nav-cluster }}
      nav-environment: prod
    secrets: inherit

  create-release:
    name: Create release
    needs: deploy-to-prod
    runs-on: ubuntu-latest
    steps:
      - uses: ncipollo/release-action@main
        with:
          tag: ${{ inputs.tag }}