name: Deploy build-tag to all environments in dev-gcp

on:
  workflow_call:
    inputs:
      image:
        required: true
        type: string

jobs:
  deploy-to-dev:
    uses: navikt/klage-workflows/.github/workflows/deploy-nais-app.yml@main
    strategy:
      matrix:
        environment: [dev,neon,argon]
    with:
      image: ${{ inputs.image }}
      nav-cluster: dev-gcp
      nav-environment: ${{ matrix.environment }}
    secrets: inherit