on:
  workflow_call:
    inputs:
      image:
        required: true
        type: string
      nav-cluster:
        required: true
        type: string
      nav-environment:
        required: true
        type: string

jobs:
  deploy-nais-app:
    name: Deploy to ${{ inputs.nav-environment }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      # sanity check
#      TODO
      - name: Check if nais/${{ inputs.nav-environment }}-config.json exists
        id: check-json
        run: echo "file-exists=$(test -f nais/${{ inputs.nav-environment }}-config.json && echo 'config_exists' || echo 'config_not_exists')" >> $GITHUB_OUTPUT
      - uses: nais/deploy/actions/deploy@v2
        if: ${{ steps.check-json.outputs.file-exists == 'config_exists' }}
        env:
          CLUSTER: ${{ inputs.nav-cluster }}
          RESOURCE: deploy/nais.yaml
          VARS: nais/${{ inputs.nav-environment }}-config.json
          VAR: image=${{ inputs.image }}
      - name: No config files detected - unable to deploy
        if: ${{ steps.check-json.outputs.file-exists != 'config_exists' }}
        run: echo "::warning title=Unable to deploy::Could not find nais/${{ inputs.nav-environment }}-config.json"